on: push
name: Test with GitHub workflow CI
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: Go Modules
      uses: cedrickring/golang-action@1.3.0
      env:
        GO111MODULE: "on"

    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.3.0
